### ISSUE TITLE
need test a sample performance at Mac OS 

### ISSUE THREAD

**Issue by shivan42** [shivan42/CodeGenUnderStorIO#2]
@artem-zinnatullin please test a [sample](https://github.com/shivan42/CodeGenUnderStorIO/tree/master/sample) on Mac OS by using .sh file (linux_run.sh)
Definition of done is creating "App" folder with other folders hierarchy and java files

**Comment by artem-zinnatullin** [comment]
Works fine! (Sorry for delay)

**Comment by artem-zinnatullin** [comment]
I guess you can rename it to `unix_run.sh` btw

**Comment by shivan42** [comment]
Super
