### ISSUE TITLE
Handling new lines within create statements

### ISSUE THREAD

**Issue by kvithayathil** [shivan42/CodeGenUnderStorIO#3]
Great utility! One bug i'm seeing is that the classes fail to generate columns if the create statements have been broken up by new lines e.g. 

**CREATE TABLE some_table (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
type_id TEXT UNIQUE,
);**

There's a couple of sql tools that generate statements in this format.

**Comment by shivan42** [comment]
@jedikv You'll right, it's not good. 
Fixed! Please check the new solution

**Comment by kvithayathil** [comment]
Cool. Thanks for the fast response!
Is that available on the latest jar? I had trouble trying to set this project up in Intellj

Edit: nevermind I see the updated jar. Seems to be working 👍

**Comment by shivan42** [comment]
Very well. 
Yes, as you already saw the .jar file at sample folder was updated too 

so, I close the issue, thank you for participating
